// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MentalEdu.Repositories.Models;

public partial class Notification
{
    public Guid Id { get; set; }

    public string DestinationScreen { get; set; }

    public bool? IsRead { get; set; }

    public string Message { get; set; }

    public string Title { get; set; }

    public string Type { get; set; }

    public int? UserId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool? ActiveFlag { get; set; }

    public virtual UserAccount User { get; set; }
}