// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MentalEdu.Repositories.Models;

public partial class Psychologist
{
    public Guid Id { get; set; }

    public int? UserId { get; set; }

    public string FullName { get; set; }

    public string LicenseNumber { get; set; }

    public int ExperienceYears { get; set; }

    public string Qualification { get; set; }

    public string ClinicAddress { get; set; }

    public string ContactEmail { get; set; }

    public string ContactPhone { get; set; }

    public string Biography { get; set; }

    public decimal ConsultationFee { get; set; }

    public string AvailabilitySchedule { get; set; }

    public string ImageUrl { get; set; }

    public double? RatingsAverage { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool? ActiveFlag { get; set; }

    public virtual ICollection<CounselingSession> CounselingSessions { get; set; } = new List<CounselingSession>();

    public virtual ICollection<PsychologistSpecialization> PsychologistSpecializations { get; set; } = new List<PsychologistSpecialization>();

    public virtual UserAccount User { get; set; }
}