// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MentalEdu.Repositories.Models;

public partial class PsychologistSpecialization
{
    public Guid Id { get; set; }

    public Guid? PsychologistId { get; set; }

    public Guid? SpecializationId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool? ActiveFlag { get; set; }

    public virtual Psychologist Psychologist { get; set; }

    public virtual Specialization Specialization { get; set; }
}