// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MentalEdu.Repositories.Models;

public partial class Report
{
    public Guid Id { get; set; }

    public int? UserId { get; set; }

    public DateTime ReportDate { get; set; }

    public string ReportType { get; set; }

    public string Content { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool? ActiveFlag { get; set; }

    public virtual UserAccount User { get; set; }
}