// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MentalEdu.Repositories.Models;

public partial class SessionFeedback
{
    public Guid Id { get; set; }

    public Guid? SessionId { get; set; }

    public int? StudentId { get; set; }

    public int Rating { get; set; }

    public string FeedbackText { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool? ActiveFlag { get; set; }

    public virtual CounselingSession Session { get; set; }

    public virtual UserAccount Student { get; set; }
}