// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MentalEdu.Repositories.Models;

public partial class UserProgram
{
    public Guid Id { get; set; }

    public int? UserId { get; set; }

    public Guid? ProgramId { get; set; }

    public string Status { get; set; }

    public int? Progress { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool? ActiveFlag { get; set; }

    public virtual SupportProgram Program { get; set; }

    public virtual UserAccount User { get; set; }
}