// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MentalEdu.BlazorApp.Models;

public partial class Appointment
{
    public Guid Id { get; set; }

    public Guid? StudentId { get; set; }

    public Guid? PsychologistId { get; set; }

    public DateTime AppointmentDate { get; set; }

    public int DurationMinutes { get; set; }

    public string Status { get; set; }

    public string Notes { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool? ActiveFlag { get; set; }

    public virtual UserAccount Psychologist { get; set; }

    public virtual UserAccount Student { get; set; }
}