// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MentalEdu.BlazorApp.Models;

public partial class BlogComment
{
    public Guid Id { get; set; }

    public Guid? BlogId { get; set; }

    public Guid? UserId { get; set; }

    public string ImageUrl { get; set; }

    public string CommentText { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool? ActiveFlag { get; set; }

    public virtual Blog Blog { get; set; }

    public virtual UserAccount User { get; set; }
}