// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MentalEdu.BlazorApp.Models;

public partial class ProgramCategory
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public string ImageUrl { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool? ActiveFlag { get; set; }

    public virtual ICollection<SupportProgram> SupportPrograms { get; set; } = new List<SupportProgram>();
}