// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MentalEdu.BlazorApp.Models;

public partial class SupportProgram
{
    public Guid Id { get; set; }

    public string ProgramName { get; set; }

    public string ImageUrl { get; set; }

    public string Description { get; set; }

    public Guid CategoryId { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public Guid? CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool? ActiveFlag { get; set; }

    public virtual ProgramCategory Category { get; set; }

    public virtual UserAccount CreatedByNavigation { get; set; }

    public virtual ICollection<UserProgram> UserPrograms { get; set; } = new List<UserProgram>();
}